### ISSUE TITLE
Titulo: Gravitans sp buff

### ISSUE THREAD

**Issue by Fefoferr** [xShut/AFISSUE#2]
La barra del gravitnas copre un ruolo fondamentale. 

- [x] - Quando la differenza di punti gravità e antigravità è compresa tra 0 e 10 , si attiva ma non viene mostrato il buff (equilibrio gravitazionale)

https://nosapki.com/it/buffs/1469

- Quando la differenza di punti gravità e antigravità supera i 10 si dovrebbero attivare di conseguenza : 

- [x] quando i punti gravità superano di 10 i punti antigravità https://nosapki.com/it/buffs/1467

- [x] mentre quando i punti antigravità superano di 10 i punti gravità:  https://nosapki.com/it/buffs/1468

- Quando invece i punti gravità/antigravità superano la soglia di 90 si dovrebbero attivare di conseguenza: 

- [x] Quando i punti gravità superano i 90 https://nosapki.com/it/buffs/4004

- [x] Quando i putni antigravità superano i 90 https://nosapki.com/it/buffs/4005

- [x] - Con i buff grandi di gravita e antigravita il colpo base deve rimuovere 2 punti gravita o antigravita (corrispettivo del buff)

**Comment by xShut** [comment]
Inserito tutto il sistema 
mancanti : 
i buff che superano il 90 riducano 90 punti 
check altro buff (skill buff)

**Comment by xShut** [comment]
inserito buff riduzione punti 
manca : colpo base quando si arriva al buff di intermezzo
