### ISSUE TITLE
Titulo: Veggente 

### ISSUE THREAD

**Issue by Fefoferr** [xShut/AFISSUE#3]
- [x] - Quando usi la ultimate Abracadabra super  https://nosapki.com/it/skills/specialist/1138 (perfavore cambiategli nome) i "cloni" evocati non attaccano il target ma attacano random 

- [x] - Quando si usa vortice di pensieri https://nosapki.com/it/skills/specialist/1135 (mindsink) il buff viene attivato https://nosapki.com/it/buffs/588 ma gli hp durante l'attacco vengono comunque scalati.

- [x] -  Quando si usa la skill Illusione https://nosapki.com/it/skills/specialist/1133 il malus "illusione" non entra https://nosapki.com/it/buffs/587 
// bisogna inserire fuga entity

**Comment by xShut** [comment]
2. fixxato 
3. fixxato (still mancanza della fuga dei mob come in fear/requiem)
